// <auto-generated />
using System;
using BreakersOfE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreakersOfE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418015706_AddSetTypeAndPricing")]
    partial class AddSetTypeAndPricing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("BreakersOfE.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("BreakersOfE.Models.ArtSeriesCard", b =>
                {
                    b.Property<int>("ArtSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageNormalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSmallUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonFoil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ArtSeriesId");

                    b.HasIndex("ScryfallId")
                        .IsUnique();

                    b.ToTable("ArtSeriesCards");
                });

            modelBuilder.Entity("BreakersOfE.Models.ArtSeriesCollectionEntry", b =>
                {
                    b.Property<int>("ArtSeriesCollectionEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoilQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ArtSeriesCollectionEntryId");

                    b.ToTable("ArtSeriesCollectionEntries");
                });

            modelBuilder.Entity("BreakersOfE.Models.CollectionEntry", b =>
                {
                    b.Property<int>("CollectionEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoilQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PoolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionEntryId");

                    b.ToTable("CollectionEntries");
                });

            modelBuilder.Entity("BreakersOfE.Models.ConspiracyCollectionEntry", b =>
                {
                    b.Property<int>("ConspiracyCollectionEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConspiracyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoilQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConspiracyCollectionEntryId");

                    b.ToTable("ConspiracyCollectionEntries");
                });

            modelBuilder.Entity("BreakersOfE.Models.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommanderPoolId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanionPoolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeckType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartnerCommanderPoolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("BreakersOfE.Models.DeckCard", b =>
                {
                    b.Property<int>("DeckCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCommander")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMaybeboard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSideboard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeckCardId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("BreakersOfE.Models.PlanarCard", b =>
                {
                    b.Property<int>("PlanarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageNormalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSmallUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonFoil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanarId");

                    b.HasIndex("ScryfallId")
                        .IsUnique();

                    b.ToTable("PlanarCards");
                });

            modelBuilder.Entity("BreakersOfE.Models.PlanarCollectionEntry", b =>
                {
                    b.Property<int>("PlanarCollectionEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoilQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanarCollectionEntryId");

                    b.ToTable("PlanarCollectionEntries");
                });

            modelBuilder.Entity("BreakersOfE.Models.PoolCard", b =>
                {
                    b.Property<int>("PoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageNormalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSmallUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMeld")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonFoil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsToken")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoyaltyOrDefense")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ManaValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceEur")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceEurFoil")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceTix")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceUsdEtched")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceUsdFoil")
                        .HasColumnType("TEXT");

                    b.Property<string>("PricesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PoolId");

                    b.HasIndex("ColorIdentity");

                    b.HasIndex("Name");

                    b.HasIndex("Rarity");

                    b.HasIndex("ScryfallId")
                        .IsUnique();

                    b.HasIndex("SetCode");

                    b.ToTable("PoolCards");
                });

            modelBuilder.Entity("BreakersOfE.Models.SchemeCard", b =>
                {
                    b.Property<int>("SchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageNormalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSmallUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonFoil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SchemeId");

                    b.HasIndex("ScryfallId")
                        .IsUnique();

                    b.ToTable("SchemeCards");
                });

            modelBuilder.Entity("BreakersOfE.Models.SchemeCollectionEntry", b =>
                {
                    b.Property<int>("SchemeCollectionEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoilQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SchemeCollectionEntryId");

                    b.ToTable("SchemeCollectionEntries");
                });

            modelBuilder.Entity("BreakersOfE.Models.TokenCard", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageNormalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSmallUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonFoil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TokenId");

                    b.HasIndex("Name");

                    b.HasIndex("ScryfallId")
                        .IsUnique();

                    b.ToTable("TokenCards");
                });

            modelBuilder.Entity("BreakersOfE.Models.TokenCollectionEntry", b =>
                {
                    b.Property<int>("TokenCollectionEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoilQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenCollectionEntryId");

                    b.ToTable("TokenCollectionEntries");
                });

            modelBuilder.Entity("BreakersOfE.Models.TradeBinderEntry", b =>
                {
                    b.Property<int>("TradeBinderEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoilQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PoolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("TradeBinderEntryId");

                    b.ToTable("TradeBinderEntries");
                });

            modelBuilder.Entity("BreakersOfE.Models.VanguardCard", b =>
                {
                    b.Property<int>("VanguardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HandModifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageNormalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSmallUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonFoil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LifeModifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VanguardId");

                    b.HasIndex("ScryfallId")
                        .IsUnique();

                    b.ToTable("VanguardCards");
                });

            modelBuilder.Entity("BreakersOfE.Models.VanguardCollectionEntry", b =>
                {
                    b.Property<int>("VanguardCollectionEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoilQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VanguardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VanguardCollectionEntryId");

                    b.ToTable("VanguardCollectionEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
